import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>7137 N Knowles Ave, Portland Oregon - For Sale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
          <h1 className={styles.title}>7137 N Knowles Ave<br/></h1>
          <h2 className={styles.title2}>Portland, OR 97217</h2>
          <p className={styles.text}>Welcome to the presale listing of our Porltand, Oregon home. <br />Coming to market Spring 2022.</p>
          <p className={styles.lh}>Features & Highlights:</p>
          <ul className={styles.list}>
            <li>Built Originally in 1969</li>
            <li>Rennovated to Open Floor Plan in 2018</li>
            <li>Gas Heat & Central Air Conditioning</li>
            <li>Large Yard Back Yard with ADU Potential</li>
          </ul>
        </div>
        <div className={styles.photos}>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 1.jpg" 
              alt="exterior front" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 2.jpg" 
              alt="exterior from right garage" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 3.jpg" 
              alt="front porch" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 4.jpg" 
              alt="entering the house" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 5.jpg" 
              alt="living space from dining area" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 6.jpg" 
              alt="living space from mudroom area" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 7.jpg" 
              alt="kitchen" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 8.jpg" 
              alt="kitchen island built ins" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 9.jpg" 
              alt="living room from kitchen" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 10.jpg" 
              alt="living room from kitchen w built ins" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 11.jpg" 
              alt="hallway to rooms" 
              layout="responsive"
              width="960"
              height="1280"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 12.jpg" 
              alt="room next to kitchen" 
              layout="responsive"
              width="960"
              height="1280"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 13.jpg" 
              alt="bathroom" 
              layout="responsive"
              width="960"
              height="1280"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 14.jpg" 
              alt="back south bedroom" 
              layout="responsive"
              width="960"
              height="1280"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 15.jpg" 
              alt="back north bedroom" 
              layout="responsive"
              width="960"
              height="1280"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 16.jpg" 
              alt="patio looking east" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 17.jpg" 
              alt="patio looking west" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 18.jpg" 
              alt="back yard" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
          <div className={styles.photo}>
            <Image 
              src="/photos/7137_n_knowles - 19.jpg" 
              alt="garage" 
              layout="responsive"
              width="1280"
              height="960"
            />
          </div>
        </div>
        <iframe 
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2792.7621994890546!2d-122.70187914812651!3d45.57522047899985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5495a7bd7bc1f033%3A0x32dd6a6f99adb851!2s7137%20N%20Knowles%20Ave%2C%20Portland%2C%20OR%2097217!5e0!3m2!1sen!2sus!4v1637274807396!5m2!1sen!2sus" 
          width="100%"
          height="420" 
          style={{ border:0 }} 
          allowfullscreen="" 
          loading="lazy"
          ></iframe>
      </main>

      <footer className={styles.footer}>
          Thank you for your interest in our home. <br />Please contact <a className={styles.link} href="https://cindyjohnson.johnlscott.com/">our agent</a> to inquire more about this opportunity.
      </footer>
    </div>
  )
}
